name: CI

on:

  push:
    branches:
      - master
      - streaming 
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-18.04, ubuntu-latest]
          python-version: ['3.6', '3.7', '3.8','3.9']
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - run: which python
      - name: Run installation.
        run: |
         pip install codecov
         pip install .[test]
         python setup.py install
      - name: Test coverage.
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
         python setup.py test
         codecov
      - name: Code Coverage
        uses: codecov/codecov-action@v1
